name = "aoc2025"
version = "0.1.0"
defaultTargets = ["aoc2025"]

[[require]]
name = "Regex"
git = "https://github.com/pandaman64/lean-regex"
rev = "v4.26.0"
subDir = "regex"

[[lean_lib]]
name = "Aoc2025"

[[lean_exe]]
name = "aoc2025"
root = "Main"
